on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, synchronize, reopened]
    branches:    
      - 'main'

jobs:
  build:
    permissions:
      contents: 'write'
      id-token: 'write'
    uses: haomapu/trigger/.github/workflows/trigger.yaml@main
    secrets: inherit
